let students = [
    "Konovalov Pavel",
    "Anofriev Ivan",
    "Asatryan Eduard",
    "Bezusov Pavel",
    "Bel'ski Dmitry",
    "Bodacheva Yana",
    "Lominsky Timofey",
    "Timonyn Igor",
    "Magasumova Alina",
    "Drey Sofya",
    "Shapovalov Ivan",
    "Grinevich Aleksandr",
    "Potemkin Georgy",
    "Dudukalov Mark",
    "Pavlova Marya",
    "Fedorkov Michail",
    "Mironchuk Dmitry",
    "Grachev Nikita",
    "Vasilov Shamil",
    "Popov Leonid",
    "Yakusheva Sofya",
];